export const AuthAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  CLEAR_REGISTER_SUCCESS: 'CLEAR_REGISTER_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_ALL: 'GET_ALL',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'GET_ALL_FAILURE',
  DELETE: 'DELETE',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAILURE: 'DELETE_FAILURE',
};

export const UiAction = {
  ALERT_SUCCESS: 'ALERT_SUCCESS',
  ALERT_ERROR: 'ALERT_ERROR',
  ALERT_CLEAR: 'ALERT_CLEAR',
  ALERT_INFO: 'ALERT_INFO',

  TOAST_SHOW: 'TOAST_SHOW',
  TOAST_CLEAR: 'TOAST_CLEAR',
  TOAST_SUCCESS: 'TOAST_SUCCESS',
};
